management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
        - "*" #Indicates that all endpoints are expose 
server:
  port: 8080 #Indicates default port for application
  servlet:
    context-path: /api/catalog #Indicate the default URL    

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/catalog?autoReconnect=true"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: false 
    generate-ddl: false
    hibernate:
      ddl-auto: validate #Indicates that the application needs to check if the entity map structure matches the table in the DB